### ISSUE TITLE
build正常，运行闪退。。

### ISSUE THREAD

**Issue by Ruoqianqian** [nihui/ncnn-android-styletransfer#5]
显示：
java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found

**Comment by joddiy** [comment]
the same problem for me

**Comment by Ruoqianqian** [comment]
> the same problem for me
I guess it is beacuse the android studio is using clang not gcc, so the openmp library can no be import suitably, but i haven‘t figure it out yet. if you solve the problem, please let me know, thanks !

**Comment by Ruoqianqian** [comment]
> the same problem for me

hey bro, i have fixed it. Just change the NDK version to r19c, which the same NDK version with pre-build ncnn-android-lib.zip

**Comment by joddiy** [comment]
Thanks, bro, I've changed the ndk version and it does work.
